version: '3'
services:
  web:
    build: .
    command: yarn dev
    ports:
      - "5000:8080"
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - frontend
      - backend
  db:
    image: mongo:4.2.7-bionic
    container_name: db
    restart: always
    volumes:
      - ./mongo-setup.sh:/docker-entrypoint-initdb.d/mongo-setup.sh:ro
      - ./data/products.json:/tmp/products.json:ro
      - ./data/collections.json:/tmp/collections.json:ro
      - ./data/showcase.json:/tmp/showcase.json:ro
    ports:
      - "5001:5432"
    networks:
      - backend
  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    ports:
      - "5002:6379"
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge